// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./json-parse-stream.js')
  await import('./schema/events.test.js')
  await import('./rl-stats-api.js')
  await import('./extract-one-object.js')

  test.resume()
}
